export const TOUR_API = {
  GET_BY_SLUG: 'http://localhost:8000/api/tours', // dùng ?slug=...
  DETAIL: 'http://localhost:8000/api/tour_details', // dùng ?tour_id=...
  IMAGES: 'http://localhost:8000/api/tour_images', // dùng ?tour_id=...
  TOP_BOOKED: 'http://localhost:8000/api/tours/top-booked',
}; 